# Generated by Django 5.0.6 on 2024-05-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scaled',
            name='low_res',
        ),
        migrations.RemoveField(
            model_name='scaled',
            name='name',
        ),
        migrations.AddField(
            model_name='scaled',
            name='input_image',
            field=models.ImageField(blank=True, null=True, upload_to='input_images/'),
        ),
        migrations.AddField(
            model_name='scaled',
            name='output_image',
            field=models.ImageField(blank=True, null=True, upload_to='output_images/'),
        ),
        migrations.AddField(
            model_name='scaled',
            name='psnr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scaled',
            name='ssim',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
