# Generated by Django 5.0.6 on 2024-05-20 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scaled',
            name='low_res',
            field=models.ImageField(upload_to='gan/files/user_inp'),
        ),
    ]
