# Generated by Django 5.0.6 on 2024-05-21 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gan', '0002_remove_scaled_low_res_remove_scaled_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scaled',
            name='ground_img',
            field=models.ImageField(blank=True, null=True, upload_to='ground_img/'),
        ),
    ]
